name: fake_store_api_client
description: "Cliente Flutter para la Fake Store API con Clean Architecture y manejo funcional de errores."
version: 1.0.2
homepage: https://github.com/juansuarez-pragma/ruta_flutter_f3
repository: https://github.com/juansuarez-pragma/ruta_flutter_f3
issue_tracker: https://github.com/juansuarez-pragma/ruta_flutter_f3/issues
topics:
  - api-client
  - http
  - rest-api
  - clean-architecture

platforms:
  android:
  ios:
  web:

environment:
  sdk: ^3.9.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
